api:
  port: 8080
mysql:
  host: host.docker.internal
  port: 3306
  username: root
  password: root
  dbname: nordic
  charset: utf8
  maxIdleConnection: 10
  maxOpenConnection: 100
services:
  categoryService: http://category_service:8080/
