export const QUEUE_TIMED_OUT_REQUEST = 'QUEUE_TIMED_OUT_REQUEST'
export const RETRY_TIMED_OUT_REQUEST = 'RETRY_TIMED_OUT_REQUEST'
export const CLEAR_TIMED_OUT_REQUEST = 'CLEAR_TIMED_OUT_REQUEST'

export const LOAD_PRODUCT = 'LOAD_PRODUCT'
export const LOAD_PRODUCT_OK = 'LOAD_PRODUCT_OK'
export const LOAD_PRODUCT_ERR = 'LOAD_PRODUCT_ERR'
